run:
	go run main.go

container:
	docker compose -f docker-compose.yml up

container-down:
	docker compose -f docker-compose.yml down

container-rm:
	docker container rm sesi3-db-1
	
volume-rm:	
	docker volume rm sesi3_db