run:
	go run main.go

container-up:
	docker compose -f docker-compose.yaml up

container-down:
	docker compose -f docker-compose.yaml down

container-rm:
	docker container rm sesi4-db-1
	
volume-rm:	
	docker volume rm sesi4_db