version: '2.16'
services:
  db:
    image: postgres:15.2-alpine3.17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=book
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./book.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local