ch1:
	go run Sesi1/challenges1.go

ch2:
	go run Sesi2/challenges2.go

ch3:
	go run Sesi3/challenges3.go

ch4: 
	go run Sesi4/biodata.go $(no)

ch5-1:
	go run Sesi5/goroutine1.go

ch5-2:
	go run Sesi5/goroutine2.go